version: 2

jobs:
  sync:
    docker:
      - image: fleshgrinder/docker-alpine-scripting
    steps:
      - checkout
      - run: ./sync

workflows:
  version: 2
  sync:
    jobs:
      - sync:
          context: github-public-token
          filters:
            branches:
              only: master
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only: master
