name: sync

on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: sync
      run: ./sync
      env:
        GITHUB_TOKEN: ${{ github.token }}
