name: sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync
        run: ./sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
